### ISSUE TITLE
Facebook login not working

### ISSUE THREAD

**Issue by danazkari** [JohnnyEstilles/keystone-social-login#7]
Hi, yesterday I tried doing a quick really simple facebook login, using the example provided by your GitHub page.

Did everything accordingly and the site crashes on your lib.

Here's the log:

``` SystemVerilog
2015-04-22T14:32:23.246244+00:00 heroku[router]: at=info method=GET path="/social/facebook/login" host=basilstore.herokuapp.com request_id=655615c4-daf4-4148-af5b-f1f71b7e5df4 fwd="201.196.212.2" dyno=web.1 connect=25ms service=15ms status=302 bytes=366
2015-04-22T14:32:23.169023+00:00 app[web.1]: GET /social/facebook/login 302 7.419 ms
2015-04-22T14:32:23.588765+00:00 app[web.1]: createCredentials() is deprecated, use tls.createSecureContext instead
2015-04-22T14:32:24.104592+00:00 app[web.1]: TypeError: undefined is not a function
2015-04-22T14:32:24.104597+00:00 app[web.1]:     at /app/node_modules/keystone-social-login/lib/start.js:98:32
2015-04-22T14:32:24.104599+00:00 app[web.1]:     at allFailed (/app/node_modules/keystone-social-login/node_modules/passport/lib/middleware/authenticate.js:87:18)
2015-04-22T14:32:24.104600+00:00 app[web.1]:     at attempt (/app/node_modules/keystone-social-login/node_modules/passport/lib/middleware/authenticate.js:160:28)
2015-04-22T14:32:24.104602+00:00 app[web.1]:     at Strategy.strategy.fail (/app/node_modules/keystone-social-login/node_modules/passport/lib/middleware/authenticate.js:277:9)
2015-04-22T14:32:24.104604+00:00 app[web.1]:     at verified (/app/node_modules/keystone-social-login/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:178:38)
2015-04-22T14:32:24.104606+00:00 app[web.1]:     at Promise.<anonymous> (/app/node_modules/keystone-social-login/lib/init.js:67:13)
2015-04-22T14:32:24.104608+00:00 app[web.1]:     at Promise.<anonymous> (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
2015-04-22T14:32:24.104610+00:00 app[web.1]:     at Promise.emit (events.js:107:17)
2015-04-22T14:32:24.104611+00:00 app[web.1]:     at Promise.emit (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
2015-04-22T14:32:24.104613+00:00 app[web.1]:     at Promise.fulfill (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
2015-04-22T14:32:24.104615+00:00 app[web.1]:     at Immediate.cb (/app/node_modules/keystone/node_modules/mongoose/lib/query.js:1150:30)
2015-04-22T14:32:24.104616+00:00 app[web.1]:     at Immediate._onImmediate (/app/node_modules/keystone/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
2015-04-22T14:32:24.104618+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:358:17)
2015-04-22T14:32:24.190932+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/social/facebook/callback?code=AQCrZPKbOF13Ai5tDE_krQloaa17kW91pUzZRq-Wl9AsbOY2GuNXNItn3XeoRSsSfEnVi-0I41rrBk8lhfo6E4CVU-sHelGHtcv0RnbHEGrMyDDkNlLwgnThDXhoOnSh_yKnfHvWZOqj3810CkXb4dVRT6Sue1gSxg_HfThfUuRfnW3W3h9eLixdQYILYahQu8wIUTfxBjCdiP2eAXT6mClZq3ZwP7syppi8gmcO0Us99XdaZe-JaOARzNuintE2imcNLc_16qEbceAtXJCx2pKW1Ed6yxJE7qiM1jZoHoHm3_D6pEwl4hcvzIGJYveAWVk" host=basilstore.herokuapp.com request_id=2caa5f55-1189-4396-898f-6f8c7fd28936 fwd="201.196.212.2" dyno=web.1 connect=2ms service=549ms status=503 bytes=0
```

I would like to know what could have happened? I've seen that node-oauth is having issues with the `createCredentials() is deprecated, use tls.createSecureContext instead` message but don't know if this is related to the site crashing and burning...

https://basilstore.herokuapp.com/social/login feel free to login with your facebook account and see for your self.

Thanks a TON for the hardwork on this lib, it's freaking amazing and I'm excited to use it and promote it!

**Comment by estilles** [comment]
@danazkari, thank you for reporting this issue. It is definitely a bug for which I will push a fix during the course of the day.

Just FYI ... the `createCredentials()` deprecation warning is unrelated. It has to do the fact that I need to update KSL to the most current version of  `passport-facebook` (See issue #5). I've scheduled this for KSL's next minor update.

Just out of curiosity, with what version of Keystone are you using KSL?

I will update this issue as soon as I get a change to push the fix.

**Comment by danazkari** [comment]
Thanks!!! Yeah I figured that was just a warning but I was driving myself mad with this bug... Good to know your active in this project, thanks for addressing my issue in such short time.

**Comment by estilles** [comment]
@danazkari ... just pushed an update that should solve your issue. Kindly test and confirm.

**Comment by danazkari** [comment]
@JohnnyEstilles good sir, it works brilliantly now, thank you so very much your work!

**Comment by estilles** [comment]
Awesome!
